# Final Project: Electra Fine Tune Model

---

**Student Name:** Mohammad Mahdi Mahboob

**Student ID:** 400387250 | mahbom2

**CodaBench Username:** mahbom2

---

### AI Tool Usage Declaration

AI was used to learn the interfaces necessary for training the model (e.g. `transformers`, `AutoTokenizer`,
`Datasets`), debug errors in code, and learn how to save and load models to prevent retraining. No code from this
notebook was uploaded to any AI, only chat interfaces were used.

| Model Name | Hardware Type | Time Used | Provider | Compute Region |
| :--- | :--- | :--- | :--- | :--- |
| Google Gemini 3 | TPUv5 Chip | 24 hrs | Google Cloud Platform | northamerica-northeast1 |

The hardware and provider information was reused from a previous homework assignment for this course.

The amount of CO2 emissions calculated is 0.2 kg, which have already been offset by the provider.

In [1]:
# Install required packages (uncomment as needed)
%pip install evaluate
# !pip install sentencepiece  # needed for some tokenizers

# Core imports
import random
import numpy as np
import pandas as pd

# HuggingFace
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer, set_seed
import evaluate

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
set_seed(SEED)

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.8.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.5 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

---
# Electra Base

## 1.1 Dataset Loading & Exploration

In [2]:
def full_text(df: pd.DataFrame):
    df['text'] = '[SENDER] ' + df['sender'].fillna('') + ' [SUBJECT] ' + df['subject'].fillna('') + ' [BODY] ' + df['body'].fillna('')

In [30]:
# TODO: Load + preprocess dataset(s)
train_csv = '/content/data/train.csv'
val_csv = '/content/data/val.csv'
test_csv = '/content/data/test.csv'

train_df = pd.read_csv(train_csv)
val_df = pd.read_csv(val_csv)
test_df = pd.read_csv(test_csv)

full_text(train_df)
full_text(val_df)
full_text(test_df)

In [31]:
from datasets import Dataset

train_ds = Dataset.from_pandas(train_df)
val_ds = Dataset.from_pandas(val_df)
test_ds = Dataset.from_pandas(test_df)

In [6]:
print(train_df.head)

<bound method NDFrame.head of                                                   sender  \
0           Leanna Hooks <kglgilqgyduehc@avnetgroup.com>
1                                             al@mpsc.ph
2                  wantEnjoy <hand@verticalcircuits.com>
3                                             Lochner <>
4      "Joe Marie J. Maja" <maja@robotics.is.tohoku.a...
...                                                  ...
10495           BREAKING NEWS <breakingnews@foxnews.com>
10496      CNN Alerts <scheerkl_1986@interdesign.com.pl>
10497           Leticia Herrera <cbkarnack@finalcom.net>
10498                 Steve Holden <gsdsz@holdenweb.com>
10499            "Kirk Umfleet" <Sidney22@webmail.co.za>

                                                receiver  \
0                                      jreitme@enron.com
1                                        <ilug@linux.ie>
2                              theorize@plg.uwaterloo.ca
3                       user7-ext4@gvc.ceas-challenge.cc
4                      Gary Livick <glivick@pacbell.net>
...                                                  ...
10495  BREAKINGNEWS Subscribers <BREAKINGNEWS-Subscri...
10496                      user8.2@gvc.ceas-challenge.cc
10497            ktwarwic <ktwarwic@speedy.uwaterloo.ca>
10498                  Neal Norwitz <vapkwvjq@gmail.com>
10499               <Undisclosed.Recipients@webnote.net>

                                        date  \
0            Fri, 04 Jan 2002 21:33:00 -0200
1      Wed, 21 Aug 2002 14:52:11 +0800 (PHT)
2            Wed, 02 May 2007 10:04:54 +0900
3            Wed, 06 Aug 2008 07:58:56 +0200
4            Mon, 24 May 1999 07:19:08 +0900
...                                      ...
10495        Mon, 16 Apr 2007 12:33:10 -0400
10496        Fri, 08 Aug 2008 05:33:36 -0400
10497        Tue, 17 Apr 2007 18:21:23 +0200
10498        Wed, 06 Aug 2008 12:03:55 -0400
10499        Mon, 25 Nov 2002 08:22:41 -0800

                                                 subject  \
0                     A new major market score each week
1                                  [ILUG] dial-on-demand
2                               Windows Vista Home Links
3                        Barely 16 and for your pleasure
4                                          Re: Using SPI
...                                                  ...
10495                                          FNC Alert
10496                        CNN Alerts: My Custom Alert
10497                                 I and hammondsport
10498  Re: [Python-Dev] First green Windows x64 build...
10499                             Did you complete this?

                                                    body  label  urls  \
0      "Stock Watch A|ert" this morning are Wysak Pet...      1     0
1      Could you please help me how to set up a dial-...      0     1
2      Logotry cool, see companies, building products...      1     0
3      \nYour girlfriend will stay by your side forev...      1     1
4      Gary Livick wrote:\n\n> I am using the SPI por...      0     0
...                                                  ...    ...   ...
10495  AT LEAST 22 SHOT AND KILLED ON CAMPUS OF VIRGI...      0     1
10496  \n\n\nCNN Alerts: My Custom Alert\n\n\n\n\n\n\...      1     0
10497  THE ALERT IS ON\nSpecial Situation Alert\n\nTM...      1     0
10498  Then put the picture on your screen and SEND M...      0     1
10499  \n\n** FREE SERVICE  \n **\n\n**  \nMortgage r...      1     1

       annotation1  annotation2  \
0              NaN          NaN
1              0.0          NaN
2              NaN          NaN
3              NaN          NaN
4              NaN          NaN
...            ...          ...
10495          NaN          NaN
10496          NaN          NaN
10497          NaN          NaN
10498          NaN          NaN
10499          NaN          NaN

                                                    text
0      [SENDER] Leanna Hooks <kglgilqgyduehc@avnetgro...
1      [SENDER] al@mpsc.ph [SUBJECT] [ILUG] dial-on-d...
2      [SENDER] wantEnjoy <hand@verticalcircuits.com>...
3      [SENDER] Lochner <> [SUBJECT] Barely 16 and fo...
4      [SENDER] "Joe Marie J. Maja" <maja@robotics.is...
...                                                  ...
10495  [SENDER] BREAKING NEWS <breakingnews@foxnews.c...
10496  [SENDER] CNN Alerts <scheerkl_1986@interdesign...
10497  [SENDER] Leticia Herrera <cbkarnack@finalcom.n...
10498  [SENDER] Steve Holden <gsdsz@holdenweb.com> [S...
10499  [SENDER] "Kirk Umfleet" <Sidney22@webmail.co.z...

[10500 rows x 10 columns]>

In [7]:
train_head = train_ds[0:10]['text']
print(train_head)

['[SENDER] Leanna Hooks <kglgilqgyduehc@avnetgroup.com> [SUBJECT] A new major market score each week [BODY] "Stock Watch A|ert" this morning are Wysak Petroleum (WYSK), Key\nEnergy Services, Inc. (Pink Sheets: KEGS), Medify So|utions (MFYS),\nSequoia Interests Corporation (SQNC).\n\nWysak Petro|eum (WYSK)\nCurrent Price:   .225\n\nWysak Petro|eum announces the signing of a Letter of Intent with the European\nCommission Ba|tic Renewab|e Energy Centre (EC BREC) to assist Wysak Petroleum in\nthe deve|opment of the Wysak Wind Power Project.\n\nEC BREC and Wysak have signed a LOI in respect to the development of a\nfu||-sized Commercial Wind Power Project in Europe. This |etter states that EC\nBREC can support Wysak in matters such as financial structuring and investment,\nregulatory issues, government policies, negotiations, wind techno|ogies, and\nother aspects re|ating to Wind Power.\n\nAbout the Wysak Wind Project\n\nThis deve|opment wil| be up to a maximum 90Mw in size and cost upwards of $120\nmi|li0n in development expenditures. Once completed, this Wind Park will supply\nupwards of 170,000 Mw of electricity annually for Po|and and the European\nCommunity. This is enough green energy to supp|y upwards of 25,000 homes with\ne|ectricity and offset near|y 170,000 tonnes of Greenhouse gases. Total gross\ne|ectric sa|es over a 20-year period are estimated at over $450 mi||i0n for a\nproject this size.\n\nAbout the EC Ba|tic Renewab|e Energy Centre\n\nThe mission of European Commission-founded EC BREC is to stimu|ate the\ndevelopment of renewable energy sources (RES) in Poland through the construction\nof RES projects, the deve|opment of innovative technologies, and the creation of\nrelevant policies, strategies and plans. To fulfill the mission, EC BREC uses\nits own research capabi|ities and cooperates with partner institutions from the\nEU, other countries, and internationa| organizations.\n\nAbout Wysak Petro|eum\n\nWysak is a diversified energy company whose goa| is to identify and deve|op\ntraditiona| fossil fuel sites, as we|l as c|ean air alternative energy producing\ntechnologies. Wysak contro|s one Wyoming Federa| oil & gas lease in the Bighorn\nBasin region and another in the Green River Basin. Its two Wyoming State leases\nare located 45 mi|es apart within the massive CoalBed Methane play area of the\nPowder River Basin. Numerous large petroleum and exploration firms operate near\nto a|l of these properties; they inc|ude ExxonMobile (XOM), Williams Gas (WMB),\nand Western Gas (WGR) among others. Co|lectively, over 26,000 we||s produced\n54.7 mi|lion barrels of oi| and 1.75 tril|ion cubic feet of natura| gas in\nWyoming\n\nConclusion:\n\nThe Examp|es Above Show The Awesome, Earning Potential of Little Known Companies\nThat Explode Onto Investor\'s Radar Screens; Many of You Are A|ready Fami|iar with This.\nIs WYSK Poised and Positioned to Do that For You?\nThen You May Feel the Time Has Come to Act... And P|ease Watch this One Trade Wednesday!\nGo WYSK.\n\nPenny stocks are considered highly specu|ative and may be unsuitable for a|l but\nvery aggressive investors.  This Profi|e is not in any way affiliated with the\nfeatured company.We were compensated 3000 dollars to distribute this report.\nThis report is for entertainment and advertising purposes only and shou|d not be\nused as investment advice.\n \nIf you wish to stop future mailings, or if you feel you have been\nwrongfully placed in our membership, please go here or send a blank\ne mail with No Thanks in the subject to   st0ck67  @yahoo.com\n\n', "[SENDER] al@mpsc.ph [SUBJECT] [ILUG] dial-on-demand [BODY] Could you please help me how to set up a dial-on-demand, what are the\npackages needed,\nand other requirements to get on.\nDo you know a site that has a how to and the package where to get it.\nPlease help me please for this was my assignment.\n\n\n\n-- \nIrish Linux Users' Group: ilug@linux.ie\nhttp://www.linux.ie/mailman/listinfo/ilug for (un)subscription information.\nList maintainer: listmaster@linux.ie", '[SENDER] wantEnjoy <hand@verticalcircuits.com> [SUBJECT] Windows Vista Home Links [BODY] Logotry cool, see companies, building products drop, innovation.\nVideos, working, group project many not, supported yourself naturally. Feeds microsoft rights reserved. Files such as valuable, relax focus. Us free newsletter, rss, feeds microsoft rights reserved terms. Age directx included, only.\nAppreciate how get simplified power management wireless networking sync!\nBlogs chats webcasts, articles eventsare vistause, our. Mahjong, titans, chess publish format updated designed! Save upgrades household computers after purchase boxed logoto. Easy copy email vistabased works background itself giving.\nSaves worry enabling key gives place adjust meeting space.\n', '[SENDER] Lochner <> [SUBJECT] Barely 16 and for your pleasure [BODY] \nYour girlfriend will stay by your side forever with our help http://www.fiftywait.com/\n\n\n', '[SENDER] "Joe Marie J. Maja" <maja@robotics.is.tohoku.ac.jp> [SUBJECT] Re: Using SPI [BODY] Gary Livick wrote:\n\n> I am using the SPI port to communicate with another Handy Board.  I have\n> written a routine in IC that will pass bytes between controllers just as\n> it is supposed to work.  However, the code is not very clean and it is\n\nGary,\n\nWe used the PA7(transmitting board) and PD0(receiving board) in wireless\nand wired mode.  This is quite easy to do.  Pete Eacmen have done the wired\nstuff while I did the wireless stuff.\n\nWith wired one, you can transmit @9600 baud with no problem.\n\nI would like to try the SPI port but my transciever module can only\ntransmit reliably at 300 baud, so I used the Asynchronous (PD0..) stuff.\n\njoema\n\n\n\n\n\n', "[SENDER] Luciano Steve <LucianoSteve@intesabci.it> [SUBJECT] Re: Bank of England Application [BODY] I would let them join, under the conditions outlined in the first paragraph ob\nBob's mail.\n\nLucinao Steve\n\nRobert Pickel wrote:\n\n> Shortly before the teleconference Board meeting two weeks ago we received an\n> application from the Bank of England for subscriber membership. When we have\n> considered central banks or government agencies for membership in the past,\n> consideration has focused on the nature of the applicant's derivatives\n> activities, its regulatory role and the type of information they are likely\n> to obtain from ISDA. Because of their derivatives activities, we have\n> generally admitted these applicants (e.g., the Kingdoms of Belgium, Denmark\n> and Sweden, the Reserve Banks of South Africa and New Zealand). We have even\n> admitted the Bank for International Settlements as a member. In general, we\n> let them know that they may not be able to receive the full range of ISDA\n> materials (e.g., draft comment letters or position papers) and that there\n> may be a need to exclude them from certain committees or discussions.\n>\n> In previous Board discussions, a higher degree of concern has been expressed\n> if, theoretically, the Federal Reserve, the Bank of Japan, the Bank of\n> England or similarly influential central banks were to apply for membership.\n> These central banks typically have a greater degree of involvement in the\n> regulatory debates (particularly on capital) and are better positioned to\n> influence the process.\n>\n> Since some of those previous debates, the regulatory role of the Bank of\n> England has diminished and the role of the Financial Services Authority has\n> correspondingly increased. The Bank of England still plays the traditional\n> central bank roles of controller of the money supply, dealing in the market\n> and lender of last resort, but the supervisory role has shifted to the FSA.\n>\n> In light of these developments, but recognizing the concerns previously\n> expressed on central bank membership, I would appreciate your views on the\n> application of the Bank of England. We have also had overtures from the Hong\n> Kong Monetary Authority regarding membership although we have not received\n> an application.\n>\n> Please share your views with the other members of the Board.\n>\n> Bob\n\n", "[SENDER] CNN Alerts <erademh1994@chronochaos.com> [SUBJECT] CNN Alerts: My Custom Alert [BODY] \n\nCNN Alerts: My Custom Alert\n\n\n\n\n\n\n \n\n\n\nAlert Name: My Custom Alert\nHeath Ledger's body exhumed\n\nFri, 8 Aug 2008 09:08:43 -0400\n\nFULL STORY\n\n\n\nYou have agreed to receive this email from CNN.com as a result of your CNN.com preference settings.\nTo manage your settings click here.\nTo alter your alert criteria or frequency or to unsubscribe from receiving custom email alerts, click here.\n\n\nCable News Network. One CNN Center, Atlanta, Georgia 30303\n© 2008 Cable News Network.\nA Time Warner Company\nAll Rights Reserved.\nView our privacy policy and terms.\n\n\n\n\n\n\n", '[SENDER] Phil McLewin <phil@mclewin.com> [SUBJECT] markup pricing [BODY] WSJ.com - Major Business News\n     \n      \n      February 15, 2002 \n     \n     \n      \n     Squeeze Cuisine: Tough Times Send\n      Chefs Looking for Cheap Substitutes\n\n      By POOJA BHATIA \n      Staff Reporter of THE WALL STREET JOURNAL\n\n\n            \n           \n      Weighing in at 11 ounces, the grilled dry-aged rib-eye with thick-sliced tomatoes and home fries was one of the best-loved entrees at 42 Degrees. So how come it\'s been dumped for a flank steak and a salad?\n\n      To save the chef $5 a portion. "I certainly do better on my margins," says James Moffat, whose San Francisco restaurant lost 40% of its business from March to December. "But I dream of the rib-eye. It was a real showpiece."\n\n      Accept no substitutes? Not quite. With business still lagging, high-end restaurants across the country are resorting to wringing savings from the menu. From Olives in Boston to Lidia\'s in Kansas City, Mo., chefs are getting rid of pricey ingredients and subbing in cheaper ones. Out: fresh ravioli, foie gras and boneless chicken breasts. In: noodles from a box, short ribs and chicken with the bone still in it. The hot seller at Firefly\'s, a barbecue joint in Marlborough, Mass.? An 8-ounce brisket on a "throne" of toast to make the portion look meatier.\n\n\n            Swapping mushrooms for white truffles cuts Lidia\'s tab for each order of risotto by $17.50\n\n           \n      Of course, the economy is a big factor, especially for restaurants. Many big expense-account eateries say business has fallen 30% in just the past year, while nationally the industry laid off 129,000 workers between August and January -- the most layoffs in any six-month period on record. "We had to save somehow," says Sam Castro, the chef de cuisine of Azie, a San Francisco restaurant where business has dropped 40% over the past year. "We weren\'t just going to sit around and wait to die."\n\n      But responding with cutbacks puts a whole new perspective on the trend du jour, comfort food, which at many restaurants has the added benefit of being cheaper food. Analysts say diners who notice such culinary sleights of hand might just get bored with the new options and eat at home. And though the industry\'s recent woes are well documented, most eateries still use a standard markup of 300% to 350%, which to many customers seems like plenty of cushion.\n\n      Andrew Nieland\'s biggest disappointment? The skimpy risotto at his favorite Italian place. It used to be loaded with sausage and porcini mushrooms. Now it\'s just cheese and basil. Mr. Nieland, a television writer in New York, says he also sees more plain grilled meats, more spaghetti in tomato sauce and way too much home-style grub. "It\'s like mashed potatoes everywhere you go," he complains.\n\n      To be sure, this is hardly the first time the nation\'s $250 billion restaurant business has tried to plump up the bottom line by downgrading ingredients. Lower-end eateries have relied on such strategies for years, cutting corners with everything from farm-raised fish to pesto from a jar. Even as the economy boomed through the late \'90s, nicer restaurants were forced to slice and dice menu items every which way to make up for high rents and labor costs.\n\n      Drop in Hype\n\n      But now, with the piling on of Sept. 11, the dot-com fallout and a drop in restaurant hype, exclusive restaurants once insulated from budget concerns are feeling the heat, too. One problem: Wealthy diners are now more sensitive about consuming conspicuously than they were six months ago. What\'s more, fine wines, which can help prop up fancy restaurants\' profits, are selling even more slowly than the highest-priced entrees.\n\n      So how are power chefs coping? Many are overhauling recipe files, swapping out pricey ingredients like foie gras and turbot for cheap ones like short ribs and halibut (switches that can lop 40% and more off the restaurant\'s cost). In Kansas City,, Lidia\'s took the seemingly minor step of introducing a new risotto-with-mushrooms dish this winter. But regulars of the popular Italian trattoria may remember the old version: chock-full of $1,200-a-pound truffles. Total savings: $17.50 an order.\n\n      Other chefs are going for the optical illusion approach, sending out bone-in steaks instead of fillets to make portions look bigger, or giving a small pork cutlet a "strategic pounding" so it takes up more dish space. Another tactic: Getting rid of labor-intensive dishes. In Chicago, the owners of Vong moved from haute-Asian fusion to simple noodle house -- changing the name to Vong\'s Thai Kitchen (VTK) -- and were able to trim the kitchen staff by 13%. "Operations are a lot more efficient when you don\'t have to make the dishes look as beautiful," says Kevin Brown, president of Lettuce Entertain You, which runs VTK.\n\n      None of this is lost on high-end suppliers, who\'ve seen a drop in orders in everything from duck fat to filet mignon. Niman Ranch, an organic livestock producer in California, says it\'s had a 33% falloff in requests for high-end cuts like New York steaks and rib-eyes and a surge in orders for cheap stuff like flatiron steaks and pork hocks. Shrinking demand has caused the price of top fish like black cod and sable to come down 10% and salmon prices to fall by a third at Wild Edibles, a New York supplier. Then there\'s Hudson Valley Foie Gras, a supplier of all things duck: Its orders have tumbled 20%.\n\n      No More Imported Fish\n\n      Of course, some diners are sympathetic to the hard choices restaurants are having to make. Out in San Francisco, technology manager Jukka Valkonen noticed at a recent lunch that Red Herring, a once impossible-to-get-into seafood house, was only a third full and that some of the imported fish had been cut from the menu. "Obviously they\'re trying to stay afloat," says Mr. Valkonen. "I\'m sure it\'s a tough decision: Do you cut corners on your food to meet your bottom line?" (The restaurant\'s manager says with business down 30% to 40%, Red Herring has changed to local sources.)\n\n      But while chefs say they\'ve had few complaints about their menu restructuring, consultants fear that lagging sales are a sign that the restaurant mania of just a year ago may be petering out for good. Some point to celebrity chefs going lower-profile, while others say even restaurant reviews are creating less buzz. People want to go "back to a kinder, gentler, pre-Emeril world," says New York restaurant consultant Clark Wolfe.\n\n      Indeed, the National Restaurant Association is so worried about the recession, it\'s launched a $2 million-plus campaign to get diners out again. And some analysts predict that, after registering 0.3% real growth in 2001, the restaurant industry will shrink 1% this year. The forecast is even worse for white-tablecloth places, which are expected to decline 5% to 10% in 2002. What\'s more, some economists fear it will be years before restaurants return to the robust growth of the late \'90s. "Oh, boy, I wouldn\'t dare predict when business will be back where it was," says Bob Goldin, vice president of Technomic, a restaurant consulting group.\n\n      Meanwhile, 42 Degrees in San Francisco is just happy to be open. And running lean has helped turn the tables: After nearly a year of red ink, it has begun to break even and is hoping to soon turn a profit. Making up the losses might take more time. "It\'ll be a happy ending," says the chef, Mr. Moffat. "Perhaps."\n\n\n--------------------------------------------------------------------------\n\n      Lower Prices, Higher Profits?\n      Facing some of the emptiest dining rooms they\'ve seen in years, high-end restaurants have begun cutting back on everything from ingredients to labor. Here\'s how chefs around the country say they\'re saving.\n\n            Restaurant  Old Dish/New Dish  Markup  Comments  \n            Luna Park\n            San Francisco  Pork chop with mashed potatoes and green beans, $13  260%  Thanks to a "strategic pounding" the smaller, cheaper cutlet covers more plate than the chop. Add potatoes and beans and you get a "dish that fills you up for not alot of money." says the owner.  \n            Pork cutlet with mashed potatoes and green beans, $13.50  415%  \n            42 Degrees\n            San Francisco  11-ounce NY Strip with home fries and organic tomatoes, $27  270%  Chef James Moffat might be saving $5 a portion on the flank steak, but "I dream of the rib-eye," he says. They\'ve also shrunk portion sizes so diners will order more desserts.  \n            6-ounce flank steak with arugula salad, $22  400%  \n            Lidia\'s\n            Kansas City  White truffle risotto, $45  217%  When the price of white truffles jumped 15% this winter, the restaurant decided to dump them. "It\'s a delicate time now, and you don\'t want to lose revenue with a high-risk dish," says one owner.  \n            Wild mushroom risotto, $12  384%  \n            Mambo Grill\n            Chicago  Sugarcane monkfish and tuna skewers, $15.95  278%  The skewers were one of the restaurant\'s least profitable dishes. At $3.25 per pound, mahi-mahi costs a third of ahi tuna or monkfish, and now the diner gets 9 oz. of fish instead of 3 1/2 oz.  \n            Coconut curried mahi-mahi, $16.95  434%  \n            Zealous\n            Chicago  Pot-au-feu with squab and grilled foie gras, $21  294%  "Everyone loves short rib, and it\'s cheap," says chef Michael Taus. "It\'s about survival this year." And diners seem to like the new version. Orders are up 50%.  \n            Pot-au-feu with duck breast and braised short rib, $14  333%  \n            Heartland Chophouse\n            New York  Prime New York strip steak, $28  278%  The sirloin is less tender, but at this price, it outsells the strip steak three to one. Other changes: Brown butcher paper replaces white tablecloths, and dried barley fronds for fresh flowers.  \n            Black angus sirloin, $24.95  444%  \n            Monkey Bar\n            New York  Texas antelope with apple compote, $32  229%  The pork chop is less intimidating, says chef David Walzog, noting it does twice the volume as the antelope. Sauces are no longer made to order but in quart-sized batches in the morning.  \n            Pork chop with onion marmalade and spinach, $28  280%  \n            Olives\n            Boston  Handmade pumpkin stuffed ravioli with lobster, $18  240%  Though the food cost is the same by using linguini from a box, the restaurant saves about 70 cents a portion in labor costs.  \n            Linguini tossed with squash and lobster, $18  240%  \n\n      Write to Pooja Bhatia at pooja.bhatia@wsj.com1\n\n           URL for this article:\n            http://online.wsj.com/article/0,,SB1013731151712145960.djm,00.html\n\n           \n           Hyperlinks in this Article:\n            (1) mailto:pooja.bhatia@wsj.com  \n\n      Updated February 15, 2002 12:01 a.m. EST\n\n\n\n\n     \n      Copyright 2002 Dow Jones & Company, Inc. All Right

In [8]:
f1_metric = evaluate.load("f1")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading builder script: 0.00B [00:00, ?B/s]

In [9]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return f1_metric.compute(predictions=predictions, references=labels)

---
## 1.2 Fine-tuning Pretrained Models (#3.1)

Select **two** different pretrained transformer models (e.g. BERT, RoBERTa, DistilBERT, DeBERTa, ModernBERT, ELECTRA, T5, …).  
The models must **not** already be fine-tuned on your specific task.

### Fine-tuned Model 1

In [10]:
MODEL_1_NAME = 'google/electra-base-discriminator'

---

#### New Model Setup

In [11]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_1_NAME)
model = AutoModelForSequenceClassification.from_pretrained( MODEL_1_NAME, num_labels=2)

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

ElectraForSequenceClassification LOAD REPORT from: google/electra-base-discriminator
Key                                               | Status     |
--------------------------------------------------+------------+-
discriminator_predictions.dense_prediction.weight | UNEXPECTED |
discriminator_predictions.dense_prediction.bias   | UNEXPECTED |
electra.embeddings_project.bias                   | UNEXPECTED |
discriminator_predictions.dense.weight            | UNEXPECTED |
electra.embeddings_project.weight                 | UNEXPECTED |
discriminator_predictions.dense.bias              | UNEXPECTED |
classifier.out_proj.bias                          | MISSING    |
classifier.dense.weight                           | MISSING    |
classifier.out_proj.weight                        | MISSING    |
classifier.dense.bias                             | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

---

#### Load Saved Model

In [ ]:
from zipfile import ZipFile

zip_name = '/content/ft_electra.zip'
with ZipFile(zip_name, 'r') as zip_f:
  zip_f.extractall('electra-ftm')

In [ ]:
model_1_path = '/content/electra-ftm'

tokenizer = AutoTokenizer.from_pretrained(model_1_path)
model = AutoModelForSequenceClassification.from_pretrained(model_1_path)

---

#### Running

In [12]:
def tknz(data):
    return tokenizer(data['text'], padding='max_length', truncation=True)

In [32]:
tok_train = train_ds.map(tknz, batched=True)
tok_val = val_ds.map(tknz, batched=True)
tok_test = test_ds.map(tknz, batched=True)

Map:   0%|          | 0/10500 [00:00<?, ? examples/s]

Map:   0%|          | 0/2250 [00:00<?, ? examples/s]

Map:   0%|          | 0/2250 [00:00<?, ? examples/s]

In [14]:
from transformers import DataCollatorWithPadding
data_col = DataCollatorWithPadding(tokenizer=tokenizer)

In [23]:
train_args = TrainingArguments(
    output_dir='/content/electra_ft',
    eval_strategy="steps",
    eval_steps=100,
    logging_steps=100,
    learning_rate=5e-5,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=4,
    per_device_eval_batch_size=8,
    eval_accumulation_steps=1,
    dataloader_num_workers=2,
    dataloader_pin_memory=True,
    fp16=True,
    group_by_length=True,
    gradient_checkpointing=True,
    num_train_epochs=3,
    weight_decay=0.01,
    save_strategy='steps',
    save_total_limit=1,
    load_best_model_at_end=True,
    report_to='none'
)

trainer = Trainer(
    model=model,
    args=train_args,
    train_dataset=tok_train,
    eval_dataset=tok_val,
    data_collator=data_col,
    compute_metrics=compute_metrics
)

In [24]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=987, training_loss=0.1642861274479612, metrics={'train_runtime': 1288.1299, 'train_samples_per_second': 24.454, 'train_steps_per_second': 0.766, 'total_flos': 8287998243840000.0, 'train_loss': 0.1642861274479612, 'epoch': 3.0})

---

#### Save

In [ ]:
save_dir = '/content/model_ft_electra'
model.save_pretrained(save_dir)
tokenizer.save_pretrained(save_dir)

In [ ]:
import shutil
zip_name = 'ft_electra'
shutil.make_archive(zip_name, 'zip', save_dir)

In [ ]:
from google.colab import files
files.download(f'/content/{zip_name}.zip')

---

#### Test

In [38]:
trainer.args.group_by_length = False
raw_pred = trainer.predict(tok_test)
test_y_pred = np.argmax(raw_pred.predictions, axis=-1)

In [42]:
from google.colab import files
submission_df = pd.DataFrame(test_y_pred, columns=['label'])
sub_file = '/content/submission.csv'
print(submission_df.head())
submission_df.to_csv(sub_file, index=False)

files.download(f'{sub_file}')

   label
0      1
1      0
2      1
3      1
4      0

---
## Code Attribution

List any code snippets, tutorials, or resources you referenced below. Include URLs and a short description of what was adapted.

| Source | URL | What was adapted |
|--------|-----|------------------|
| HuggingFace Trainer tutorial | https://huggingface.co/docs/transformers/training | Fine-tuning loop scaffold |
| *(add more rows as needed)* | | |